Controllers/InstrumentController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using bsis3a_webapp.Data;
using bsis3a_webapp.Models;
using bsis3a_webapp.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace bsis3a_webapp.Controllers
{
 
    public class InstrumentController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _hostingEnvironment;
        
        [BindProperty]
        public InstrumentViewModel InstrumentVM { get; set; }

        public InstrumentController(ApplicationDbContext db, IWebHostEnvironment hostingEnvironment)
        {
            _db = db;
            _hostingEnvironment = hostingEnvironment;

            InstrumentVM = new InstrumentViewModel()
            {
                Items = _db.Items.ToList(),
                Types = _db.Types.ToList(),
                Instrument = new Models.Instrument()
            };
        }

        [HttpGet]
        public IActionResult Index()
        {
            var instrument = _db.Instruments.Include(m => m.Item).Include(m => m.Type);
            return View(instrument);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(InstrumentVM);
        }

        [HttpPost]
        [ActionName("Create")]
        public IActionResult CreatePost()
        {
            if(ModelState.IsValid)
            {
                _db.Instruments.Add(InstrumentVM.Instrument); 
                
                _db.SaveChanges();

                

                SaveImage();
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(InstrumentVM);
        }
     public void SaveImage()
        {
                var InstrumentId = InstrumentVM.Instrument.Id;

                string wwwrootPath = _hostingEnvironment.WebRootPath;

                var files = HttpContext.Request.Form.Files;

                var saveInstrument = _db.Instruments.Find(InstrumentId);

                if(files.Count != 0)
                {
                    var ImagePath = @"images\instrument\";
                    var Extension = Path.GetExtension(files[0].FileName);
                    var RelativeImagePath = ImagePath + InstrumentId + Extension;
                    var AbsImagePath = Path.Combine(wwwrootPath, RelativeImagePath);

                    using (var fileStream = new FileStream(AbsImagePath, FileMode.Create))
                    {
                        files[0].CopyTo(fileStream);
                    }
                    saveInstrument.ImagePath = RelativeImagePath;
                }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            InstrumentVM.Instrument = _db.Instruments.Include(m => m.Item).Include(m => m.Type).SingleOrDefault(m => m.Id == id);
            if(InstrumentVM.Instrument== null)
            {
                return NotFound();
            }
            return View(InstrumentVM);
       }
       
         [HttpPost]
        [ActionName("Edit")]
        public IActionResult EditPost()
       {
            if(ModelState.IsValid)
            {
                _db.Instruments.Update(InstrumentVM.Instrument);
                
               SaveImage();
               _db.SaveChanges();
               return RedirectToAction("Index");
            }
            return View(InstrumentVM);
       }
 
        [HttpPost]
        [ActionName("Delete")]
        public IActionResult Delete(int id)
        {
            var instrument = _db.Instruments.Find(id);
            if(instrument == null)
            {
                return NotFound();
            }
            _db.Instruments.Remove(instrument);
            _db.SaveChanges();
            return RedirectToAction("Index");
         } 
    } 
}

Controllers/ItemController.cs
using System.Collections.Generic;
using bsis3a_webapp.Data;
using bsis3a_webapp.Models;
using Microsoft.AspNetCore.Mvc;

namespace bsis3a_webapp.Controllers
{
     public class ItemController : Controller
     {
         private readonly ApplicationDbContext _db;

         public ItemController( ApplicationDbContext db)
         {
             _db = db;
         }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<Item> itemList = _db.Items;
            return View (itemList);
        }

        [HttpGet]
        public IActionResult Create()
        {   
            return View();
        }

        [HttpPost]
         public IActionResult Create(Item item)
        { 
            if(ModelState.IsValid)
            {
                _db.Items.Add(item);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {   
            var item = _db.Items.Find(id);
            if(item == null)
            {
                return NotFound();
            }
            return View(item);
        }

         [HttpPost]
         public IActionResult Edit(Item item)
        { 
            if(ModelState.IsValid)
            {
                _db.Items.Update(item);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {   
            var item = _db.Items.Find(id);
            if(item == null)
            {
                return NotFound();
            }
            return View(item);
        }

         [HttpPost]
         [ActionName("Delete")]
        public IActionResult DeletePost(int id)
        {   
            var item = _db.Items.Find(id);
            if(item == null)
            {
                return NotFound();
            }
            _db.Items.Remove(item);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

     }
}

Controllers/TypeController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using bsis3a_webapp.Data;
using bsis3a_webapp.Models;
using bsis3a_webapp.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;


namespace bsis3a_webapp.Controllers
{
     public class TypeController : Controller
     {
         private readonly ApplicationDbContext _db;

        [BindProperty]
         public TypeViewModel TypeVM { get; set; }

         public TypeController( ApplicationDbContext db)
         {
             _db = db;

             TypeVM = new TypeViewModel()
             {
                 Items = _db.Items.ToList(),
                 Type = new Models.Type()
             };
         }

        [HttpGet]
        public IActionResult Index()
        {
            var type = _db.Types.Include(m=> m.Item);
            return View (type);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View(TypeVM);
            
        }

        [HttpPost]
        [ActionName("Create")]
        public IActionResult CreatePost()
        {
            if(ModelState.IsValid)
            {
                _db.Types.Add(TypeVM.Type);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(TypeVM);
            
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            TypeVM.Type = _db.Types.Include(m => m.Item).SingleOrDefault(m => m.Id == id);
            if(TypeVM.Type == null)
            {
                return NotFound();
            }
            return View(TypeVM);
            
        }

         [HttpPost]
        [ActionName("Edit")]
        public IActionResult EditPost()
        {
            if(ModelState.IsValid)
            {
                _db.Types.Update(TypeVM.Type);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(TypeVM);
            
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            TypeVM.Type = _db.Types.Include(m => m.Item).SingleOrDefault(m => m.Id == id);
            if(TypeVM.Type == null)
            {
                return NotFound();
            }
            return View(TypeVM);
            
        }

        
         [HttpPost]
        [ActionName("Delete")]
        public IActionResult DeletePost(int id)
        {
            var type = _db.Types.Find(id);
            if(type == null)
            {
                 return NotFound();
            }
                _db.Types.Remove(type);
                _db.SaveChanges();
                return RedirectToAction("Index");
            
        }


     }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - bsis3a-webapp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header>
       <nav class="navbar navbar-expand-lg navbar-light bg-primary">
           <div class="container">         
  <a class="navbar-brand" href="#">BSIS 3A </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
          Manage
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" asp-controller="Item" asp-action="Index">Item</a>
          <a class="dropdown-item" asp-controller="Type" asp-action="Index">Type</a>
           <a class="dropdown-item" asp-controller="Instrument" asp-action="Index">Instruments</a>
          
        </div>
      </li>
    </ul>
    </div>
  </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - bsis3a_webapp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>